export { default as Location } from "./icons/location.png";
export { default as Phone } from "./icons/Phone.png";
export { default as Envelope } from "./icons/Envelope.png";
export { default as ArrowDown } from "./icons/arrow-down.png";
export { default as ArrowRight } from "./icons/arrow-right.png";
export { default as Logo } from "./logo/logo.png";
export { default as IlomaLogo } from "./iloma.png";
export { default as Send } from "./icons/send.png";
export { default as Shape1 } from "./shapes/shape1.png";
export { default as Shape2 } from "./shapes/shape2.png"
export { default as Shape3 } from "./shapes/shape3.png";
export { default as Shape4 } from "./shapes/shape4.png";
export { default as Shape5 } from "./shapes/shape5.png";
export { default as PhoneGreen } from "./icons/phone-green.png";
export { default as Banner } from "./banner/banner.png";
export { default as Image1 } from "./img1.png";
export { default as Image2 } from "./img2.png";
export { default as Check } from "./icons/check.png";
export { default as CreativeIcon } from "./icons/creative-icon.png";
export { default as Hardworking } from "./icons/hardworking.png";
export { default as Supportive } from "./icons/supportive.png";
export { default as Passionate } from "./icons/passionate.png";
export { default as ArrowTopRightBlack } from "./icons/arrow-top-right-black.png";
export { default as StarIcon } from "./icons/star-fill.png";
export { default as Contact } from "./contact/contact-img.png";
export { default as Placeholder } from "../img/icons/placeholder.png"
export { default as Thumsup } from "../img/icons/thums-up.png"
export { default as Bag } from "../img/icons/bag.png"
export { default as Users } from "../img/icons/users.png"
export { default as Trophy } from "../img/icons/trophy.png"
export { default as CeoImage } from "../img/team/amol.png"
export { default as Team1 } from "../img/team/t1.png"
export { default as Team2 } from "../img/team/t2.png"
export { default as Team3 } from "../img/team/t3.png"
export { default as Team4 } from "../img/team/t4.png"
export { default as Service1 } from "../img/s1.png"
export { default as Service2 } from "../img/s2.png"
export { default as Service3 } from "../img/s3.png"
export { default as IOS } from "../img/ios.png"
export { default as Close } from "../img/icons/close.png"
export { default as WorkDetail } from "../img/work/work-detail.png"
export { default as GooglePlayStore } from "../img/work/google-play-store.png"
export { default as AppleStore } from "../img/work/app-store.png"
export { default as User } from "../img/blog/User.png"
export { default as Tags } from "../img/blog/tags.png"
export { default as Calendar } from "../img/blog/calendar.png"
export { default as GalleryImg } from "../img/icons/gallery.png"
import { default as Location } from "./icons/location.png";


